--  -- Structure de la table `departement` --   
-- CREATE TABLE `departement` ( 
-- `ID_DEPARTEMENT` int(11) NOT NULL AUTO_INCREMENT, 
-- `ID_REGION` int(11) NOT NULL default '', 
-- `NOM` char(32) default NULL,
-- PRIMARY KEY (`ID_DEPARTEMENT`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;  
--  -- Contenu de la table `departement` --   
 INSERT INTO `departement` VALUES ('01', '22', 'Ain');
 INSERT INTO `departement` VALUES ('02', '20', 'Aisne');
 INSERT INTO `departement` VALUES ('03', '03', 'Allier');
 INSERT INTO `departement` VALUES ('04', '18', 'Alpes de haute provence');
 INSERT INTO `departement` VALUES ('05', '18', 'Hautes alpes');
 INSERT INTO `departement` VALUES ('06', '18', 'Alpes maritimes');
 INSERT INTO `departement` VALUES ('07', '22', 'Ardèche');
 INSERT INTO `departement` VALUES ('08', '08', 'Ardennes');
 INSERT INTO `departement` VALUES ('09', '16', 'Ariège');
 INSERT INTO `departement` VALUES ('10', '08', 'Aube');
 INSERT INTO `departement` VALUES ('11', '13', 'Aude');
 INSERT INTO `departement` VALUES ('12', '16', 'Aveyron');
 INSERT INTO `departement` VALUES ('13', '18', 'Bouches du rhône');
 INSERT INTO `departement` VALUES ('14', '04', 'Calvados');
 INSERT INTO `departement` VALUES ('15', '03', 'Cantal');
 INSERT INTO `departement` VALUES ('16', '21', 'Charente');
 INSERT INTO `departement` VALUES ('17', '21', 'Charente maritime');
 INSERT INTO `departement` VALUES ('18', '07', 'Cher');
 INSERT INTO `departement` VALUES ('19', '14', 'Corrèze');
 INSERT INTO `departement` VALUES ('21', '05', 'Côte d\'or');
 INSERT INTO `departement` VALUES ('22', '06', 'Côtes d\'Armor');
 INSERT INTO `departement` VALUES ('23', '14', 'Creuse');
 INSERT INTO `departement` VALUES ('24', '02', 'Dordogne');
 INSERT INTO `departement` VALUES ('25', '10', 'Doubs');
 INSERT INTO `departement` VALUES ('26', '22', 'Drôme');
 INSERT INTO `departement` VALUES ('27', '11', 'Eure'); 
 INSERT INTO `departement` VALUES ('28', '07', 'Eure et Loir');
 INSERT INTO `departement` VALUES ('29', '06', 'Finistère');
 INSERT INTO `departement` VALUES ('30', '13', 'Gard'); 
 INSERT INTO `departement` VALUES ('31', '16', 'Haute garonne');
 INSERT INTO `departement` VALUES ('32', '16', 'Gers'); 
 INSERT INTO `departement` VALUES ('33', '02', 'Gironde');
 INSERT INTO `departement` VALUES ('34', '13', 'Hérault');
 INSERT INTO `departement` VALUES ('35', '06', 'Ile et Vilaine');
 INSERT INTO `departement` VALUES ('36', '07', 'Indre'); 
 INSERT INTO `departement` VALUES ('37', '07', 'Indre et Loire');
 INSERT INTO `departement` VALUES ('38', '22', 'Isère'); 
 INSERT INTO `departement` VALUES ('39', '10', 'Jura'); 
 INSERT INTO `departement` VALUES ('40', '02', 'Landes'); 
 INSERT INTO `departement` VALUES ('41', '07', 'Loir et Cher'); 
 INSERT INTO `departement` VALUES ('42', '22', 'Loire'); 
 INSERT INTO `departement` VALUES ('43', '03', 'Haute loire'); 
 INSERT INTO `departement` VALUES ('44', '19', 'Loire Atlantique');
 INSERT INTO `departement` VALUES ('45', '07', 'Loiret');
 INSERT INTO `departement` VALUES ('46', '16', 'Lot'); 
 INSERT INTO `departement` VALUES ('47', '02', 'Lot et Garonne'); 
 INSERT INTO `departement` VALUES ('48', '13', 'Lozère');
 INSERT INTO `departement` VALUES ('49', '19', 'Maine et Loire');
 INSERT INTO `departement` VALUES ('50', '04', 'Manche'); 
 INSERT INTO `departement` VALUES ('51', '08', 'Marne'); 
 INSERT INTO `departement` VALUES ('52', '08', 'Haute Marne');
 INSERT INTO `departement` VALUES ('53', '19', 'Mayenne');
 INSERT INTO `departement` VALUES ('54', '15', 'Meurthe et Moselle');
 INSERT INTO `departement` VALUES ('55', '15', 'Meuse'); 
 INSERT INTO `departement` VALUES ('56', '06', 'Morbihan'); 
 INSERT INTO `departement` VALUES ('57', '15', 'Moselle');
 INSERT INTO `departement` VALUES ('58', '05', 'Nièvre');
 INSERT INTO `departement` VALUES ('59', '17', 'Nord');
 INSERT INTO `departement` VALUES ('60', '20', 'Oise'); 
 INSERT INTO `departement` VALUES ('61', '04', 'Orne'); 
 INSERT INTO `departement` VALUES ('62', '17', 'Pas de Calais'); 
 INSERT INTO `departement` VALUES ('63', '03', 'Puy de Dôme'); 
 INSERT INTO `departement` VALUES ('64', '02', 'Pyrénées Atlantiques');
 INSERT INTO `departement` VALUES ('65', '16', 'Hautes Pyrénées');
 INSERT INTO `departement` VALUES ('66', '13', 'Pyrénées Orientales');
 INSERT INTO `departement` VALUES ('67', '01', 'Bas Rhin'); 
 INSERT INTO `departement` VALUES ('68', '01', 'Haut Rhin'); 
 INSERT INTO `departement` VALUES ('69', '22', 'Rhône'); 
 INSERT INTO `departement` VALUES ('70', '10', 'Haute Saône'); 
 INSERT INTO `departement` VALUES ('71', '05', 'Saône et Loire');
 INSERT INTO `departement` VALUES ('72', '19', 'Sarthe'); 
 INSERT INTO `departement` VALUES ('73', '22', 'Savoie');
 INSERT INTO `departement` VALUES ('74', '22', 'Haute Savoie');
 INSERT INTO `departement` VALUES ('75', '12', 'Paris');
 INSERT INTO `departement` VALUES ('76', '11', 'Seine Maritime');
 INSERT INTO `departement` VALUES ('77', '12', 'Seine et Marne');
 INSERT INTO `departement` VALUES ('78', '12', 'Yvelines');
 INSERT INTO `departement` VALUES ('79', '21', 'Deux Sèvres');
 INSERT INTO `departement` VALUES ('80', '20', 'Somme');
 INSERT INTO `departement` VALUES ('81', '16', 'Tarn');
 INSERT INTO `departement` VALUES ('82', '16', 'Tarn et Garonne');
 INSERT INTO `departement` VALUES ('83', '18', 'Var');
 INSERT INTO `departement` VALUES ('84', '18', 'Vaucluse');
 INSERT INTO `departement` VALUES ('85', '19', 'Vendée');
 INSERT INTO `departement` VALUES ('86', '21', 'Vienne'); 
 INSERT INTO `departement` VALUES ('87', '14', 'Haute Vienne');
 INSERT INTO `departement` VALUES ('88', '15', 'Vosge');
 INSERT INTO `departement` VALUES ('89', '05', 'Yonne');
 INSERT INTO `departement` VALUES ('90', '10', 'Territoire de Belfort'); 
 INSERT INTO `departement` VALUES ('91', '12', 'Essonne'); 
 INSERT INTO `departement` VALUES ('92', '12', 'Haut de seine'); 
 INSERT INTO `departement` VALUES ('93', '12', 'Seine Saint Denis');
 INSERT INTO `departement` VALUES ('94', '12', 'Val de Marne'); 
 INSERT INTO `departement` VALUES ('95', '12', 'Val d\'Oise');
 INSERT INTO `departement` VALUES ('2a', '09', 'Corse du Sud'); 
 INSERT INTO `departement` VALUES ('2b', '09', 'Haute Corse');