INSERT INTO `vadore_LiveAnim`.`types` ( `ID_FAMILLE_TYPES`, `ID_TYPES`) VALUES 
 ( 'Type de message', 'Message personnel'),
 ( 'Type de message', 'News'),
 ( 'Type de message', 'Alerte'),
 ( 'Type de message', 'FAQ'),
 ( 'Type de message', 'MàJ'),
 ( 'Type de pack', 'Basique'),
 ( 'Type de pack', 'Spécial'),
 ( 'Type de personne', 'Organisateur'),
 ( 'Type de personne', 'Prestataire'),
 ( 'Type de personne', 'Admin'), 
 ( 'Type de soirée', 'Soirée dansante'),
 ( 'Type de soirée', 'Anniversaire'), 
 ( 'Type de soirée', 'Boom'), 
 ( 'Type de soirée', 'Spectacle'),
 ( 'Type de soirée', 'Repas'),
 ( 'Type de soirée', 'Boite de nuit'),
 ( 'Statut du message', 'Non lu'),
 ( 'Statut du message', 'Lu'), 
 ( 'Statut du message', 'Répondu'),
 ( 'Statut du message', 'Supprimé'),
 ( 'Statut du contrat', 'En attente'),
 ( 'Statut du contrat', 'Validé'),
 ( 'Statut du contrat', 'Refusé'),
 ( 'Statut du contrat', 'Annulé'),
 ( 'Découverte du site', 'Facebook'),
 ( 'Découverte du site', 'Twitter'),
 ( 'Découverte du site', 'Google+'), 
 ( 'Découverte du site', 'MySpace'),
 ( 'Découverte du site', 'Moteur de recherche Google'),
 ( 'Découverte du site', 'Moteur de recherche autre'),
 ( 'Découverte du site', 'Par un ami'), 
 ( 'Découverte du site', 'Par e-mail'),
 ( 'Découverte du site', 'Pubs'), 
 ( 'Découverte du site', 'Autres'),
 ( 'Evaluation', '00'),
 ( 'Evaluation', '01'),
 ( 'Evaluation', '02'), 
 ( 'Evaluation', '03'), 
 ( 'Evaluation', '04'),
 ( 'Evaluation', '05'),
 ( 'Evaluation', '06'), 
 ( 'Evaluation', '07'), 
 ( 'Evaluation', '08'),
 ( 'Evaluation', '09'), 
 ( 'Evaluation', '10'), 
 ( 'Civilité', 'Mr'),
 ( 'Civilité', 'Mme'), 
 ( 'Civilité', 'Mlle'),
 ( 'Caractéristiques', 'Relationnel'),
 ( 'Caractéristiques', 'Prestation'),
 ( 'Caractéristiques', 'Ponctualité'),
 ( 'Caractéristiques', 'Vestimentaire'),
 ( 'Caractéristiques', 'Ambiance'),
 ( 'Caractéristiques', 'Gestion de son matériel');